name: AdminToolbox
version: '${version}'
authors: [ Karltroid, iLynxcat ]
main: org.modernbeta.admintoolbox.AdminToolboxPlugin
api-version: '1.21.4'
folia-supported: true
softdepend: [ BlueMap, LuckPerms, PlaceholderAPI ]

default-permission: op
permissions:
  admintoolbox.manage:
    description: Can use the AdminToolbox management command.
  admintoolbox.manage.reload:
    description: Can reload AdminToolbox's configuration.
    children: [ admintoolbox.manage ]
  admintoolbox.target:
    description: Can spectate at current location.
  admintoolbox.target.player:
    description: Can spectate at a player's location.
    children: [ admintoolbox.target ]
  admintoolbox.target.location:
    description: Can spectate at provided coordinates.
    children: [ admintoolbox.target ]
  admintoolbox.spawn:
    description: Can spectate at current world spawn.
  admintoolbox.spawn.all:
    description: Can spectate at all world spawns.
    children: [ admintoolbox.spawn ]
  admintoolbox.fullbright:
    description: Can enable fullbright preference.
  admintoolbox.reveal:
    description: Can reveal while spectating in admin mode.
  admintoolbox.freeze:
    description: Can freeze and unfreeze players.
  admintoolbox.yell:
    description: Can show titles to other players.
  admintoolbox.broadcast.receive:
    description: Can receive alerts about other admins' actions.
  admintoolbox.broadcast.exempt:
    description: Admin actions will not alert others who can receive them.
    default: false
  # Legacy catch-all admin permission. Children list is designed to be
  # backwards-compatible with pre-1.0.0 versions of AdminToolbox.
  admintoolbox.admin:
    description: (Deprecated) Can perform core AdminToolbox actions.
    children:
      - admintoolbox.target
      - admintoolbox.target.player
      - admintoolbox.target.location
      - admintoolbox.reveal
      - admintoolbox.freeze
      - admintoolbox.yell
      - admintoolbox.broadcast.receive
  admintoolbox.streamermode:
    description: Can enter and exit streamer mode.
  admintoolbox.streamermode.unlimited:
    description: Can bypass maximum duration in streamer mode.
    default: false
  admintoolbox.streamermode.placeholder.wear:
    description: Can wear placeholder while in streamer mode.
    default: true
  admintoolbox.streamermode.placeholder.view:
    description: Can see other players' streamer mode status placeholder.
    default: op

commands:
  admintoolbox:
    description: Manage the AdminToolbox plugin.
    usage: /<command> <reload>
    permission: admintoolbox.manage
    aliases: [ atb ]
  spectate:
    description: Spectate in admin mode, optionally at a provided location.
    usage: |
      /<command> [player]
      /<command> <x> [y] <z> [world]
    permission: admintoolbox.target
    aliases: [ admin, spec, target ]
  reveal:
    description: Reveal to other players while spectating in admin mode.
    usage: /<command>
    permission: admintoolbox.reveal
    aliases: [ show ]
  back:
    description: Teleport backward in admin teleport history.
    usage: /<command>
    permission: admintoolbox.target
    aliases: [ last, previous, prev ]
  forward:
    description: Teleport forward in admin teleport history.
    usage: /<command>
    permission: admintoolbox.target
    aliases: [ next ]
  freeze:
    description: Freeze a player, removing their ability to move or interact with the world.
    usage: /<command> <player>
    permission: admintoolbox.freeze
    aliases: [ capture ]
  unfreeze:
    description: Unfreeze a frozen player.
    usage: /<command> <player>
    permission: admintoolbox.freeze
    aliases: [ release ]
  spawn:
    description: Enter admin mode at a given world spawn.
    usage: /<command> [world]
    aliases: [ targetspawn ]
    permission: admintoolbox.spawn
  fullbright:
    description: Enable a Night Vision preference while spectating.
    usage: /<command> [on|off]
    aliases: [ fb, nightvision, nv ]
    permission: admintoolbox.fullbright
  streamermode:
    description: Enter streamer mode, temporarily disabling certain privileges.
    usage: /<command> [duration]
    aliases: [ sm, pausealerts, pa ]
    permission: admintoolbox.streamermode
